[project]
name = "thrive-well-fastapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "gunicorn>=23.0.0",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.34.0",
]
