import sqlmodel

"""revamped columns for large int

Revision ID: 04b59e0749ed
Revises: 99d6c536679f
Create Date: 2025-04-19 15:17:29.347608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04b59e0749ed"
down_revision: Union[str, None] = "99d6c536679f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("updated_on", sa.DateTime(), nullable=False))
    op.alter_column(
        "user",
        "telegram_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.drop_column("user", "updated_o")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "updated_o", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "user",
        "telegram_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("user", "updated_on")
    # ### end Alembic commands ###
