import sqlmodel

"""change timestamp to datetime

Revision ID: ecdc5b77b3ee
Revises: 9907c93ab706
Create Date: 2025-04-26 16:36:43.497353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ecdc5b77b3ee"
down_revision: Union[str, None] = "9907c93ab706"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        ALTER TABLE message
        ALTER COLUMN timestamp TYPE TIMESTAMP WITHOUT TIME ZONE
        USING to_timestamp(timestamp)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message",
        "timestamp",
        existing_type=sa.DateTime(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
